name = "gg-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env]
CRAWL_API = "/api/crawl"

[[durable_objects.bindings]]
name = "CRAWL_SESSION"
class_name = "CrawlSession"

[[migrations]]
tag = "v1"
new_classes = ["CrawlSession"]
